Add apidoc
nawi-hub/proteuslib pull request #221
Opened 2021-09-08 15:47 UTC by dangunter

## Fixes/Addresses: 

Adding auto-generated API docs back in to the repo. Including instructions for how to generate them.

Question: do we need to check the ``apidoc/*.rst`` files in to Git?

## Summary/Motivation:

If the auto-generated API doc files are there, references in code docstrings between pieces should be navigable. Also, it's just nice to have.

## Changes proposed in this PR:
- add commands for Windows and Linux/OSX to generate API docs with correct options 
- add developer documentation
- add appropriate TOC entries for the generated API docs

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2021-09-09 17:55 UTC, lbianchi-lbl requested changes
I've checked the built apidocs on ReadTheDocs, and I think they look awesome. The accompanying developer docs also look good. I left a couple of questions and comments, mostly on test robustness.

2021-09-09 20:23 UTC, TimBartholomew submitted a review, later dismissed

2021-09-17 16:32 UTC, lbianchi-lbl commented
I'll keep an eye on this after #223 is merged to see how the test behaves when no docs directory is found, and possibly just add a `pyest.skip()` if needed.

2021-09-20 19:49 UTC, dangunter commented on docs/getting_started/install.rst
> +   * On Linux/OSX run ``./apidoc.sh``
We could add that too, but (a) make/gmake is not as ubiquitous in Windows as Mac/Linux, (b) modifying Sphinx Makefiles is a little less obvious than these extremely simple scripts.

2021-09-20 19:54 UTC, dangunter commented on proteuslib/tests/test_docs.py
> +
Fine to expose this more formally, but the sphinx check seems like added complexity to me.

This is a little worrisome for reasons you don't describe, i.e. can I mess with formatting in a way to "fool" it? Maybe.

2021-09-21 03:56 UTC, dangunter commented
@lbianchi-lbl I added skip. I think it would have worked anyways, but now it does everything except check for Sphinx. That still strikes me as fragile, who knows why it might not be in the path.

2021-09-23 20:11 UTC, TimBartholomew approved these changes

2021-09-23 20:18 UTC, merged